name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  run-unit-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt update -y
          sudo apt install emacs
          emacs -batch -l ert -l tests.el -f ert-run-tests-batch-and-exit